# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './src/main/resources/ui_qt/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(1146, 767)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setAnimated(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_network = QtWidgets.QVBoxLayout()
        self.verticalLayout_network.setObjectName("verticalLayout_network")
        self.groupBox_network = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox_network.sizePolicy().hasHeightForWidth())
        self.groupBox_network.setSizePolicy(sizePolicy)
        self.groupBox_network.setObjectName("groupBox_network")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_network)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_network)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_5.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.groupBox_devileList = QtWidgets.QGroupBox(self.groupBox_network)
        self.groupBox_devileList.setObjectName("groupBox_devileList")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_devileList)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget_network = QtWidgets.QTableWidget(self.groupBox_devileList)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_network.sizePolicy().hasHeightForWidth())
        self.tableWidget_network.setSizePolicy(sizePolicy)
        self.tableWidget_network.setRowCount(0)
        self.tableWidget_network.setColumnCount(6)
        self.tableWidget_network.setObjectName("tableWidget_network")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_network.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_network.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_network.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_network.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_network.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_network.setHorizontalHeaderItem(5, item)
        self.tableWidget_network.horizontalHeader().setVisible(True)
        self.tableWidget_network.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_network.horizontalHeader().setDefaultSectionSize(79)
        self.tableWidget_network.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_3.addWidget(self.tableWidget_network)
        self.horizontalLayout_2.addWidget(self.groupBox_devileList)
        self.groupBox_une = QtWidgets.QGroupBox(self.groupBox_network)
        self.groupBox_une.setObjectName("groupBox_une")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_une)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_une)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_6.addWidget(self.textBrowser)
        self.horizontalLayout_2.addWidget(self.groupBox_une)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 5)
        self.horizontalLayout_2.setStretch(2, 4)
        self.verticalLayout_network.addWidget(self.groupBox_network)
        self.horizontalLayout_serial = QtWidgets.QHBoxLayout()
        self.horizontalLayout_serial.setObjectName("horizontalLayout_serial")
        self.groupBox_serial = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_serial.sizePolicy().hasHeightForWidth())
        self.groupBox_serial.setSizePolicy(sizePolicy)
        self.groupBox_serial.setObjectName("groupBox_serial")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_serial)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_port = QtWidgets.QGroupBox(self.groupBox_serial)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_port.sizePolicy().hasHeightForWidth())
        self.groupBox_port.setSizePolicy(sizePolicy)
        self.groupBox_port.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_port.setObjectName("groupBox_port")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_port)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.comboBox_port = QtWidgets.QComboBox(self.groupBox_port)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_port.sizePolicy().hasHeightForWidth())
        self.comboBox_port.setSizePolicy(sizePolicy)
        self.comboBox_port.setCurrentText("")
        self.comboBox_port.setObjectName("comboBox_port")
        self.verticalLayout_4.addWidget(self.comboBox_port)
        self.verticalLayout.addWidget(self.groupBox_port)
        self.pushButton_reloadPorts = QtWidgets.QPushButton(self.groupBox_serial)
        self.pushButton_reloadPorts.setObjectName("pushButton_reloadPorts")
        self.verticalLayout.addWidget(self.pushButton_reloadPorts)
        self.pushButton_connect = QtWidgets.QPushButton(self.groupBox_serial)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_connect.sizePolicy().hasHeightForWidth())
        self.pushButton_connect.setSizePolicy(sizePolicy)
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.verticalLayout.addWidget(self.pushButton_connect)
        self.pushButton_disconnect = QtWidgets.QPushButton(self.groupBox_serial)
        self.pushButton_disconnect.setObjectName("pushButton_disconnect")
        self.verticalLayout.addWidget(self.pushButton_disconnect)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_serial.addWidget(self.groupBox_serial)
        self.groupBox_config = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_config.setObjectName("groupBox_config")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_config)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tableWidget_config = QtWidgets.QTableWidget(self.groupBox_config)
        self.tableWidget_config.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget_config.setRowCount(0)
        self.tableWidget_config.setColumnCount(2)
        self.tableWidget_config.setObjectName("tableWidget_config")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_config.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_config.setHorizontalHeaderItem(1, item)
        self.tableWidget_config.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_config.horizontalHeader().setDefaultSectionSize(210)
        self.tableWidget_config.horizontalHeader().setHighlightSections(True)
        self.tableWidget_config.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_7.addWidget(self.tableWidget_config)
        self.horizontalLayout_configButtons = QtWidgets.QHBoxLayout()
        self.horizontalLayout_configButtons.setObjectName("horizontalLayout_configButtons")
        self.pushButton_rdConfig = QtWidgets.QPushButton(self.groupBox_config)
        self.pushButton_rdConfig.setObjectName("pushButton_rdConfig")
        self.horizontalLayout_configButtons.addWidget(self.pushButton_rdConfig)
        self.pushButton_resetConfig = QtWidgets.QPushButton(self.groupBox_config)
        self.pushButton_resetConfig.setObjectName("pushButton_resetConfig")
        self.horizontalLayout_configButtons.addWidget(self.pushButton_resetConfig)
        self.pushButton_wrConfig = QtWidgets.QPushButton(self.groupBox_config)
        self.pushButton_wrConfig.setObjectName("pushButton_wrConfig")
        self.horizontalLayout_configButtons.addWidget(self.pushButton_wrConfig)
        self.verticalLayout_7.addLayout(self.horizontalLayout_configButtons)
        self.horizontalLayout_serial.addWidget(self.groupBox_config)
        self.groupBox_console = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_console.sizePolicy().hasHeightForWidth())
        self.groupBox_console.setSizePolicy(sizePolicy)
        self.groupBox_console.setObjectName("groupBox_console")
        self.verticalLayout_1 = QtWidgets.QVBoxLayout(self.groupBox_console)
        self.verticalLayout_1.setContentsMargins(12, -1, -1, -1)
        self.verticalLayout_1.setObjectName("verticalLayout_1")
        self.textBrowser_console = QtWidgets.QTextBrowser(self.groupBox_console)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_console.sizePolicy().hasHeightForWidth())
        self.textBrowser_console.setSizePolicy(sizePolicy)
        self.textBrowser_console.setReadOnly(True)
        self.textBrowser_console.setObjectName("textBrowser_console")
        self.verticalLayout_1.addWidget(self.textBrowser_console)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.pushButton_clear = QtWidgets.QPushButton(self.groupBox_console)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_clear.sizePolicy().hasHeightForWidth())
        self.pushButton_clear.setSizePolicy(sizePolicy)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.horizontalLayout_3.addWidget(self.pushButton_clear)
        self.horizontalLayout_3.setStretch(0, 5)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout_1.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_serial.addWidget(self.groupBox_console)
        self.horizontalLayout_serial.setStretch(0, 2)
        self.horizontalLayout_serial.setStretch(1, 5)
        self.horizontalLayout_serial.setStretch(2, 5)
        self.verticalLayout_network.addLayout(self.horizontalLayout_serial)
        self.verticalLayout_network.setStretch(0, 4)
        self.verticalLayout_network.setStretch(1, 3)
        self.verticalLayout_2.addLayout(self.verticalLayout_network)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1146, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_network.setTitle(_translate("MainWindow", "RTLS Network"))
        self.groupBox.setTitle(_translate("MainWindow", "Device configuration"))
        self.pushButton.setText(_translate("MainWindow", "Refresh"))
        self.groupBox_devileList.setTitle(_translate("MainWindow", "Device List"))
        self.tableWidget_network.setSortingEnabled(True)
        item = self.tableWidget_network.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "IP"))
        item = self.tableWidget_network.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_network.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Type"))
        item = self.tableWidget_network.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Mode"))
        item = self.tableWidget_network.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Rx/Tx"))
        item = self.tableWidget_network.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Error"))
        self.groupBox_une.setTitle(_translate("MainWindow", "UNE"))
        self.groupBox_serial.setTitle(_translate("MainWindow", "Serial Port"))
        self.groupBox_port.setTitle(_translate("MainWindow", "Choose port"))
        self.pushButton_reloadPorts.setText(_translate("MainWindow", "Refresh"))
        self.pushButton_connect.setText(_translate("MainWindow", " Connect"))
        self.pushButton_disconnect.setText(_translate("MainWindow", "Disconnect"))
        self.groupBox_config.setTitle(_translate("MainWindow", "Configuration"))
        self.tableWidget_config.setSortingEnabled(True)
        item = self.tableWidget_config.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Param"))
        item = self.tableWidget_config.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        self.pushButton_rdConfig.setText(_translate("MainWindow", "Read"))
        self.pushButton_resetConfig.setText(_translate("MainWindow", "Reset"))
        self.pushButton_wrConfig.setText(_translate("MainWindow", "Write"))
        self.groupBox_console.setTitle(_translate("MainWindow", "Console Log"))
        self.pushButton_clear.setText(_translate("MainWindow", "Clear"))
