# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './src/main/resources/ui_qt/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(1146, 767)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setAnimated(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_serial = QtWidgets.QWidget()
        self.tab_serial.setObjectName("tab_serial")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_serial)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_serial = QtWidgets.QHBoxLayout()
        self.horizontalLayout_serial.setObjectName("horizontalLayout_serial")
        self.groupBox_serial = QtWidgets.QGroupBox(self.tab_serial)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_serial.sizePolicy().hasHeightForWidth())
        self.groupBox_serial.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_serial.setFont(font)
        self.groupBox_serial.setObjectName("groupBox_serial")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_serial)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_port = QtWidgets.QGroupBox(self.groupBox_serial)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_port.sizePolicy().hasHeightForWidth())
        self.groupBox_port.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_port.setFont(font)
        self.groupBox_port.setObjectName("groupBox_port")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_port)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.comboBox_port = QtWidgets.QComboBox(self.groupBox_port)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_port.sizePolicy().hasHeightForWidth())
        self.comboBox_port.setSizePolicy(sizePolicy)
        self.comboBox_port.setCurrentText("")
        self.comboBox_port.setObjectName("comboBox_port")
        self.verticalLayout_4.addWidget(self.comboBox_port)
        self.verticalLayout.addWidget(self.groupBox_port)
        self.pushButton_reloadPorts = QtWidgets.QPushButton(self.groupBox_serial)
        self.pushButton_reloadPorts.setObjectName("pushButton_reloadPorts")
        self.verticalLayout.addWidget(self.pushButton_reloadPorts)
        self.pushButton_connect = QtWidgets.QPushButton(self.groupBox_serial)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_connect.sizePolicy().hasHeightForWidth())
        self.pushButton_connect.setSizePolicy(sizePolicy)
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.verticalLayout.addWidget(self.pushButton_connect)
        self.pushButton_disconnect = QtWidgets.QPushButton(self.groupBox_serial)
        self.pushButton_disconnect.setObjectName("pushButton_disconnect")
        self.verticalLayout.addWidget(self.pushButton_disconnect)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_serial)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(180, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_serialStatus = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_serialStatus.sizePolicy().hasHeightForWidth())
        self.label_serialStatus.setSizePolicy(sizePolicy)
        self.label_serialStatus.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(False)
        self.label_serialStatus.setFont(font)
        self.label_serialStatus.setTextFormat(QtCore.Qt.AutoText)
        self.label_serialStatus.setObjectName("label_serialStatus")
        self.horizontalLayout.addWidget(self.label_serialStatus)
        self.verticalLayout.addWidget(self.groupBox_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_serial.addWidget(self.groupBox_serial)
        self.groupBox_config = QtWidgets.QGroupBox(self.tab_serial)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_config.setFont(font)
        self.groupBox_config.setObjectName("groupBox_config")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_config)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tableWidget_config = QtWidgets.QTableWidget(self.groupBox_config)
        self.tableWidget_config.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget_config.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.tableWidget_config.setAlternatingRowColors(True)
        self.tableWidget_config.setRowCount(0)
        self.tableWidget_config.setColumnCount(2)
        self.tableWidget_config.setObjectName("tableWidget_config")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_config.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_config.setHorizontalHeaderItem(1, item)
        self.tableWidget_config.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_config.horizontalHeader().setDefaultSectionSize(180)
        self.tableWidget_config.horizontalHeader().setHighlightSections(True)
        self.tableWidget_config.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_7.addWidget(self.tableWidget_config)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_rdConfig = QtWidgets.QPushButton(self.groupBox_config)
        self.pushButton_rdConfig.setObjectName("pushButton_rdConfig")
        self.gridLayout.addWidget(self.pushButton_rdConfig, 0, 0, 1, 1)
        self.pushButton_wrConfig = QtWidgets.QPushButton(self.groupBox_config)
        self.pushButton_wrConfig.setObjectName("pushButton_wrConfig")
        self.gridLayout.addWidget(self.pushButton_wrConfig, 0, 1, 1, 1)
        self.pushButton_defConfig = QtWidgets.QPushButton(self.groupBox_config)
        self.pushButton_defConfig.setObjectName("pushButton_defConfig")
        self.gridLayout.addWidget(self.pushButton_defConfig, 0, 2, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout)
        self.horizontalLayout_serial.addWidget(self.groupBox_config)
        self.groupBox_console = QtWidgets.QGroupBox(self.tab_serial)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_console.sizePolicy().hasHeightForWidth())
        self.groupBox_console.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_console.setFont(font)
        self.groupBox_console.setObjectName("groupBox_console")
        self.verticalLayout_1 = QtWidgets.QVBoxLayout(self.groupBox_console)
        self.verticalLayout_1.setContentsMargins(12, -1, -1, -1)
        self.verticalLayout_1.setObjectName("verticalLayout_1")
        self.textBrowser_console = QtWidgets.QTextBrowser(self.groupBox_console)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_console.sizePolicy().hasHeightForWidth())
        self.textBrowser_console.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser_console.setFont(font)
        self.textBrowser_console.setAcceptDrops(False)
        self.textBrowser_console.setAccessibleName("")
        self.textBrowser_console.setAutoFormatting(QtWidgets.QTextEdit.AutoNone)
        self.textBrowser_console.setReadOnly(True)
        self.textBrowser_console.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.textBrowser_console.setOpenLinks(False)
        self.textBrowser_console.setObjectName("textBrowser_console")
        self.verticalLayout_1.addWidget(self.textBrowser_console)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pushButton_clear = QtWidgets.QPushButton(self.groupBox_console)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_clear.sizePolicy().hasHeightForWidth())
        self.pushButton_clear.setSizePolicy(sizePolicy)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.horizontalLayout_3.addWidget(self.pushButton_clear)
        self.horizontalLayout_3.setStretch(0, 5)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout_1.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_serial.addWidget(self.groupBox_console)
        self.horizontalLayout_serial.setStretch(1, 5)
        self.horizontalLayout_serial.setStretch(2, 5)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_serial)
        self.tabWidget.addTab(self.tab_serial, "")
        self.tab_network = QtWidgets.QWidget()
        self.tab_network.setObjectName("tab_network")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_network)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_network = QtWidgets.QWidget(self.tab_network)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_network.sizePolicy().hasHeightForWidth())
        self.widget_network.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.widget_network.setFont(font)
        self.widget_network.setObjectName("widget_network")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_network)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.widget_network)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tableWidget_network = QtWidgets.QTableWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_network.sizePolicy().hasHeightForWidth())
        self.tableWidget_network.setSizePolicy(sizePolicy)
        self.tableWidget_network.setRowCount(0)
        self.tableWidget_network.setColumnCount(6)
        self.tableWidget_network.setObjectName("tableWidget_network")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_network.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_network.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_network.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_network.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_network.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_network.setHorizontalHeaderItem(5, item)
        self.tableWidget_network.horizontalHeader().setVisible(False)
        self.tableWidget_network.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_network.horizontalHeader().setDefaultSectionSize(65)
        self.tableWidget_network.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_5.addWidget(self.tableWidget_network)
        self.pushButton_refreshNet = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_refreshNet.setObjectName("pushButton_refreshNet")
        self.verticalLayout_5.addWidget(self.pushButton_refreshNet)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget_network)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tableWidget_config_2 = QtWidgets.QTableWidget(self.groupBox_3)
        self.tableWidget_config_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget_config_2.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.tableWidget_config_2.setAlternatingRowColors(True)
        self.tableWidget_config_2.setRowCount(0)
        self.tableWidget_config_2.setColumnCount(2)
        self.tableWidget_config_2.setObjectName("tableWidget_config_2")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_config_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_config_2.setHorizontalHeaderItem(1, item)
        self.tableWidget_config_2.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_config_2.horizontalHeader().setDefaultSectionSize(205)
        self.tableWidget_config_2.horizontalHeader().setHighlightSections(True)
        self.tableWidget_config_2.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_8.addWidget(self.tableWidget_config_2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_rdConfig_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_rdConfig_2.setObjectName("pushButton_rdConfig_2")
        self.gridLayout_2.addWidget(self.pushButton_rdConfig_2, 0, 0, 1, 1)
        self.pushButton_wrConfig_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_wrConfig_2.setObjectName("pushButton_wrConfig_2")
        self.gridLayout_2.addWidget(self.pushButton_wrConfig_2, 0, 1, 1, 1)
        self.pushButton_defConfig_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_defConfig_2.setObjectName("pushButton_defConfig_2")
        self.gridLayout_2.addWidget(self.pushButton_defConfig_2, 0, 2, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_2)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.verticalLayout_3.setStretch(0, 2)
        self.verticalLayout_3.setStretch(1, 2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.groupBox_une = QtWidgets.QGroupBox(self.widget_network)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_une.setFont(font)
        self.groupBox_une.setTitle("")
        self.groupBox_une.setObjectName("groupBox_une")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_une)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_mpl = QtWidgets.QWidget(self.groupBox_une)
        self.widget_mpl.setObjectName("widget_mpl")
        self.verticalLayout_6.addWidget(self.widget_mpl)
        self.horizontalLayout_2.addWidget(self.groupBox_une)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 4)
        self.horizontalLayout_4.addWidget(self.widget_network)
        self.tabWidget.addTab(self.tab_network, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout_network = QtWidgets.QVBoxLayout()
        self.verticalLayout_network.setObjectName("verticalLayout_network")
        self.verticalLayout_2.addLayout(self.verticalLayout_network)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1146, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "POSIT Configurator"))
        self.groupBox_serial.setTitle(_translate("MainWindow", "Serial Port"))
        self.groupBox_port.setTitle(_translate("MainWindow", "Choose port"))
        self.pushButton_reloadPorts.setText(_translate("MainWindow", "Refresh"))
        self.pushButton_connect.setText(_translate("MainWindow", " Connect"))
        self.pushButton_disconnect.setText(_translate("MainWindow", "Disconnect"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Status"))
        self.label_serialStatus.setText(_translate("MainWindow", "No device found."))
        self.groupBox_config.setTitle(_translate("MainWindow", "Configuration"))
        self.tableWidget_config.setSortingEnabled(True)
        item = self.tableWidget_config.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Param"))
        item = self.tableWidget_config.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        self.pushButton_rdConfig.setText(_translate("MainWindow", "Read"))
        self.pushButton_wrConfig.setText(_translate("MainWindow", "Write"))
        self.pushButton_defConfig.setText(_translate("MainWindow", "Reset to default settings"))
        self.groupBox_console.setTitle(_translate("MainWindow", "Console Log"))
        self.pushButton_clear.setText(_translate("MainWindow", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_serial), _translate("MainWindow", "Serial"))
        self.groupBox.setTitle(_translate("MainWindow", "Device List"))
        self.tableWidget_network.setSortingEnabled(True)
        item = self.tableWidget_network.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "IP"))
        item = self.tableWidget_network.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_network.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Type"))
        item = self.tableWidget_network.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Mode"))
        item = self.tableWidget_network.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Rx/Tx"))
        item = self.tableWidget_network.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Error"))
        self.pushButton_refreshNet.setText(_translate("MainWindow", "Refresh"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Configuration"))
        self.tableWidget_config_2.setSortingEnabled(True)
        item = self.tableWidget_config_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Param"))
        item = self.tableWidget_config_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        self.pushButton_rdConfig_2.setText(_translate("MainWindow", "Read"))
        self.pushButton_wrConfig_2.setText(_translate("MainWindow", "Write"))
        self.pushButton_defConfig_2.setText(_translate("MainWindow", "Reset to default settings"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_network), _translate("MainWindow", "Network"))
