# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './src/main/resources/ui_qt/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_network = QtWidgets.QVBoxLayout()
        self.verticalLayout_network.setObjectName("verticalLayout_network")
        self.groupBox_network = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox_network.sizePolicy().hasHeightForWidth())
        self.groupBox_network.setSizePolicy(sizePolicy)
        self.groupBox_network.setObjectName("groupBox_network")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_network)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_todo = QtWidgets.QLabel(self.groupBox_network)
        self.label_todo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_todo.setObjectName("label_todo")
        self.horizontalLayout_2.addWidget(self.label_todo)
        self.verticalLayout_network.addWidget(self.groupBox_network)
        self.horizontalLayout_serial = QtWidgets.QHBoxLayout()
        self.horizontalLayout_serial.setObjectName("horizontalLayout_serial")
        self.groupBox_serial = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_serial.sizePolicy().hasHeightForWidth())
        self.groupBox_serial.setSizePolicy(sizePolicy)
        self.groupBox_serial.setObjectName("groupBox_serial")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_serial)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_port = QtWidgets.QGroupBox(self.groupBox_serial)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_port.sizePolicy().hasHeightForWidth())
        self.groupBox_port.setSizePolicy(sizePolicy)
        self.groupBox_port.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_port.setObjectName("groupBox_port")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_port)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.comboBox_port = QtWidgets.QComboBox(self.groupBox_port)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_port.sizePolicy().hasHeightForWidth())
        self.comboBox_port.setSizePolicy(sizePolicy)
        self.comboBox_port.setCurrentText("")
        self.comboBox_port.setObjectName("comboBox_port")
        self.verticalLayout_4.addWidget(self.comboBox_port)
        self.verticalLayout.addWidget(self.groupBox_port)
        self.pushButton_reloadPorts = QtWidgets.QPushButton(self.groupBox_serial)
        self.pushButton_reloadPorts.setObjectName("pushButton_reloadPorts")
        self.verticalLayout.addWidget(self.pushButton_reloadPorts)
        self.pushButton_connect = QtWidgets.QPushButton(self.groupBox_serial)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_connect.sizePolicy().hasHeightForWidth())
        self.pushButton_connect.setSizePolicy(sizePolicy)
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.verticalLayout.addWidget(self.pushButton_connect)
        self.pushButton_clear = QtWidgets.QPushButton(self.groupBox_serial)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_clear.sizePolicy().hasHeightForWidth())
        self.pushButton_clear.setSizePolicy(sizePolicy)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.verticalLayout.addWidget(self.pushButton_clear)
        self.horizontalLayout_serial.addWidget(self.groupBox_serial)
        self.groupBox_console = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_console.sizePolicy().hasHeightForWidth())
        self.groupBox_console.setSizePolicy(sizePolicy)
        self.groupBox_console.setObjectName("groupBox_console")
        self.verticalLayout_1 = QtWidgets.QVBoxLayout(self.groupBox_console)
        self.verticalLayout_1.setContentsMargins(12, -1, -1, -1)
        self.verticalLayout_1.setObjectName("verticalLayout_1")
        self.textBrowser_console = QtWidgets.QTextBrowser(self.groupBox_console)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_console.sizePolicy().hasHeightForWidth())
        self.textBrowser_console.setSizePolicy(sizePolicy)
        self.textBrowser_console.setReadOnly(True)
        self.textBrowser_console.setObjectName("textBrowser_console")
        self.verticalLayout_1.addWidget(self.textBrowser_console)
        self.horizontalLayout_serial.addWidget(self.groupBox_console)
        self.verticalLayout_network.addLayout(self.horizontalLayout_serial)
        self.verticalLayout_2.addLayout(self.verticalLayout_network)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_network.setTitle(_translate("MainWindow", "Network Config"))
        self.label_todo.setText(_translate("MainWindow", "TODO"))
        self.groupBox_serial.setTitle(_translate("MainWindow", "Serial Port"))
        self.groupBox_port.setTitle(_translate("MainWindow", "Choose port"))
        self.pushButton_reloadPorts.setText(_translate("MainWindow", "Reload Ports"))
        self.pushButton_connect.setText(_translate("MainWindow", " Connect"))
        self.pushButton_clear.setText(_translate("MainWindow", "Clear Console"))
        self.groupBox_console.setTitle(_translate("MainWindow", "Console Log"))
